apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zho
rules:
{{- range .Values.clusterRole.rules }}
  - apiGroups: {{ include "zho.stringSlice" .apiGroups }}
    resources:  {{ include "zho.stringSlice" .resources }}
    verbs: {{ include "zho.stringSlice" .verbs }}
{{- end }}
